### ISSUE TITLE
De alt kan beter leeg gehouden worden

### ISSUE THREAD

**Issue by CathelijneVisser** [CelinexPutte/the-startup-responsive-interactieve-website#14]
https://github.com/CelinexPutte/the-startup-responsive-interactieve-website/blob/aa13b2442c1a20f8279413115aaac9937decbbe3/index.html#L34

**Comment by CelinexPutte** [comment]
Cyd zei juist de code review daarvoor dat ik juist de alt teksten moest invullen 😂
