### ISSUE TITLE
Is dit wel een link? :)

### ISSUE THREAD

**Issue by KrijnHoetmer** [CelinexPutte/the-startup-responsive-interactieve-website#15]
Code kopiëren is prima natuurlijk, maar maak het wel van jezelf. (En kom langs of DM me bij vragen :))

https://github.com/CelinexPutte/the-startup-responsive-interactieve-website/blob/aa13b2442c1a20f8279413115aaac9937decbbe3/index.html#L49

**Comment by CelinexPutte** [comment]
Ik heb er nu een `<div>` van gemaakt!
