### ISSUE TITLE
Change `.nav-show` to `nav-show`

### ISSUE THREAD

**Issue by M4TThys123** [CelinexPutte/the-startup-responsive-interactieve-website#3]
https://github.com/CelinexPutte/the-startup-responsive-interactieve-website/blob/99bf2924de6441b98de9a76a2037ac619abde7af/main.js#L7

**New code**
```JavaScript
function menuToggle() {
	menu.classList.toggle("nav-show");
}
```

**Comment by CelinexPutte** [comment]
Gelukt, hij werkt nu!
